Adding reply callback to deployFeed and adding using it for canary failures
getsentry/eng-pipes pull request #627
Opened 2023-09-25 16:29 UTC by IanWoodard

Adding a new callback to the deployFeed which enables returning slack blocks to be sent as a reply to a sent message as a follow up. The first usage of this is sending a reply following a canary failure explaining that the pipeline is paused and tagging the people involved (those who have commits in the failing deploy).

2023-09-25 20:08 UTC, mattgauntseo-sentry requested changes
Will chat about tests in a bit

2023-09-25 20:32 UTC, IanWoodard commented on src/brain/gocdSlackFeeds/index.ts
> +      const uniqueAuthors = authors.filter(
The one downside to filtering after the getUser call is that we would be making unnecessary calls to getUser (which isn't trivial). But overall, I agree.

2023-09-26 17:01 UTC, mattgauntseo-sentry approved these changes

2023-09-26 17:52 UTC, IanWoodard commented on src/brain/gocdSlackFeeds/index.test.ts
> +    await db('users').insert(user);
I removed the db usage

2023-09-26 19:50 UTC, mattgauntseo-sentry commented
LGTM

2023-09-26 21:03 UTC, merged